name: Java & React CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Backend Setup (Java) ---
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test backend
        working-directory: ./backend
        run: |
          ./mvnw clean verify

      # --- Frontend Setup (Node + React) ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and test frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run test -- --watchAll=false
